name: Test, Build & Redeploy UI

on:
  push:
    branches: [ main ]
    paths:
      - src/ui/**
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: |
        cd src/ui
        npm install
        
    - name: Build
      run: |
        cd src/ui
        npm run build
        
  docker:
    name: Publish
    runs-on: ubuntu-18.04
    needs: [build]
    env:
      REPO: ${{ secrets.DOCKER_REPO_UI }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to REPO
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} src/ui
      - name: Publish Image
        run: docker push $REPO
        
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-18.04
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL_UI }}
